# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('endereco', models.CharField(max_length=1024)),
                ('telefone', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAssociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cidades', to='core.Estado'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bairros', to='core.Cidade'),
        ),
        migrations.AddField(
            model_name='associado',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bairro'),
        ),
        migrations.AddField(
            model_name='associado',
            name='tipo_associado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoAssociado'),
        ),
    ]
